package com.example.accessibilitydemo_compose.ui.theme
import androidx.compose.ui.graphics.Color


val md_theme_light_primary = Color(0xFFab00a0)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFffd7f4)
val md_theme_light_onPrimaryContainer = Color(0xFF390036)
val md_theme_light_secondary = Color(0xFF6e5868)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFf8daed)
val md_theme_light_onSecondaryContainer = Color(0xFF271623)
val md_theme_light_tertiary = Color(0xFF815343)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFffdbce)
val md_theme_light_onTertiaryContainer = Color(0xFF321206)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfcfcfc)
val md_theme_light_onBackground = Color(0xFF1f1a1d)
val md_theme_light_surface = Color(0xFFfcfcfc)
val md_theme_light_onSurface = Color(0xFF1f1a1d)
val md_theme_light_surfaceVariant = Color(0xFFefdee7)
val md_theme_light_onSurfaceVariant = Color(0xFF4f444b)
val md_theme_light_outline = Color(0xFF80747b)
val md_theme_light_inverseOnSurface = Color(0xFFf8eef2)
val md_theme_light_inverseSurface = Color(0xFF342f32)
val md_theme_light_inversePrimary = Color(0xFFffabed)
val md_theme_light_shadow = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFffabed)
val md_theme_dark_onPrimary = Color(0xFF5d0058)
val md_theme_dark_primaryContainer = Color(0xFF83007c)
val md_theme_dark_onPrimaryContainer = Color(0xFFffd7f4)
val md_theme_dark_secondary = Color(0xFFdbbfd1)
val md_theme_dark_onSecondary = Color(0xFF3e2a39)
val md_theme_dark_secondaryContainer = Color(0xFF564050)
val md_theme_dark_onSecondaryContainer = Color(0xFFf8daed)
val md_theme_dark_tertiary = Color(0xFFf5b9a4)
val md_theme_dark_onTertiary = Color(0xFF4c2618)
val md_theme_dark_tertiaryContainer = Color(0xFF663c2d)
val md_theme_dark_onTertiaryContainer = Color(0xFFffdbce)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF1f1a1d)
val md_theme_dark_onBackground = Color(0xFFe9e0e3)
val md_theme_dark_surface = Color(0xFF1f1a1d)
val md_theme_dark_onSurface = Color(0xFFe9e0e3)
val md_theme_dark_surfaceVariant = Color(0xFF4f444b)
val md_theme_dark_onSurfaceVariant = Color(0xFFd2c2cb)
val md_theme_dark_outline = Color(0xFF9b8d95)
val md_theme_dark_inverseOnSurface = Color(0xFF1f1a1d)
val md_theme_dark_inverseSurface = Color(0xFFe9e0e3)
val md_theme_dark_inversePrimary = Color(0xFFab00a0)
val md_theme_dark_shadow = Color(0xFF000000)



val seed = Color(0xFFc516b7)
val error = Color(0xFFba1b1b)